### ISSUE TITLE
Wrong parsing useragents string on www.useragents.me

### ISSUE THREAD

**Issue by Eriter555** [DavideViolante/useragents-me-api#16]
Some strings end with a dot, some strings clearly lack numbers at the end. Such (compatible; Google-Read-Aloud; +https://support.google.com/webmasters/answer/1061943 usergents are no good either. 

Thanks for project.

**Comment by DavideViolante** [comment]
I don't do any parsing, I just get user agents from useragents.me. If the parsing is wrong there, you can contact the author of the website. Let me know.
